apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-secret
  namespace: external-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: k8s-secret
    creationPolicy: Owner
  data:
  - secretKey: username  # key in the kubernetes secret
    remoteRef:
      key: id:9058f8a2-31de-4406-85a2-bf96132fd2fc
      version: latest_enabled

