---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: external-secrets
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: d0377c53-93b5-4ce5-9150-d51a5153e218
      accessKey:
        secretRef:
          name: very-secret
          key: access-key
      secretKey:
        secretRef:
          name: very-secret
          key: secret-access-key
