---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: default
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: 1b278a9d-c985-4c38-9c5e-95a61514f067
      accessKey:
        secretRef:
          name: very-secret
          key: access-key
      secretKey:
        secretRef:
          name: very-secret
          key: secret-access-key
