---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      interval: 12h
  values:
    installCRDs:
      true

# ---
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: secret-store
#   namespace: default
# spec:
#   provider:
#     scaleway:
#       region:
#         secretRef:
#           name: external-secrets
#           key: access-key
#       projectId:
#         secretRef:
#           name: external-secrets
#           key: access-key
#       accessKey:
#         secretRef:
#           name: external-secrets
#           key: access-key
#       secretKey:
#         secretRef:
#           name: external-secrets
#           key: secret-access-key

